### ISSUE TITLE
EF Async

### ISSUE THREAD

**Issue by dsaperry** [thinktecture/Thinktecture.IdentityServer.v3.EntityFramework#38]
I noticed while reviewing this project that all the Stores (which have async signatures), do not actually utilize EF's async methods or the async/await pattern.

Was this done for a specific reason, is it on the roadmap, or is this something that can be PR'd in?

Thanks!

**Comment by brockallen** [comment]
Yea, good point... *facepalm*

**Comment by brockallen** [comment]
Done on dev branch. Feel free to double check it. Thx.

**Comment by dsaperry** [comment]
Awesome! I believe ClientStore and ScopeStore still have some EF methods that can be asynced. Also, BaseDbContext overrides SaveChanges to better log EntityValidationExceptions, but now everything should be calling the async version which isn't overridden. 

Thanks again!

**Comment by brockallen** [comment]
For the client and scope stores, they're not looking up the entities by the DB PK, so I didn't see any other async API other than FindAsync which uses the PK. Am I missing something?

I added the validation reporting into SaveChangesAsync.

**Comment by dsaperry** [comment]
ClientStore can use SingleOrDefaultAsync, and ScopeStore can use ToListAsync.

**Comment by brockallen** [comment]
Ah cool. ok...

**Comment by brockallen** [comment]
Ok, done. There were several more queries that I missed since I didn't have the namespace in scope. Very nice. Thanks.

**Comment by dsaperry** [comment]
Great, thanks!
